blank_issues_enabled: false
contact_links:
  - name: View existing issues
    url: https://github.com/inori-3333/AKIS-Issue-Report/issues
    about: Please search for existing issues before submitting a new one.
